services:
  reverse_proxy:
    image: nginx:stable
    container_name: reverse_proxy
    ports:
      - "8000:80"  # Host port exposed to ngrok
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network

  hello-fastapi:
    image: evdev3/hello-fastapi:latest
    container_name: hello-fastapi
    expose:
      - "8000"
    networks:
      - app-network

  transcription-api:
    image: evdev3/transcription-api:latest
    container_name: transcription-api
    expose:
      - "8000"
    env_file:
    - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge